freifunk/directory.api.freifunk.net

directory.json

move api file duesseldorf.json into the correct repository.

update community Düsseldorf

---

tests/test.py

Get the community-files in parallel using threads and improve status messages
@samarjeet27 and @andibraeu Can you please check if this is ok!

get urls in parallel to improve test speed

---

directory.json

> updated emskirchen
> change to new netmon-updated api-file
Netmon aktualisiert hier automatisch nodecount und Lastchange(bei Bedarf)

updated emskirchen

---

directory.json

added coburg (Freifunk Franken)

---

directory.json

Updating API-Address for Wiesbaden

API-Address for Wiesbaden has changed

---

directory.json

Funkfeuer Wien hat nun auch endlich ein API file.

add FunkFeuer Wien

---

directory.json

Freifunk Ehingen ist nicht länger aktiv.

removed ehingen

---

directory.json

Hi, 
can you please pull this patch into main repo. I had to update the url for dresden freifunk.
Thanks a lot
Stephan

update dresden url

---

directory.json

Signed-off-by: Sven Velt <sven@velt.de>

Add Schwabach

---

directory.json

Please add Freifunk Wismar. Thanks, Mathias

added freifunk wismar (opennet e.V. sub-community)

---

directory.json

Insert Weyher Pfalz

---

directory.json

change url for leichlingen

---

directory.json

essen-steele is part of the community essen.

remove essen-steele

---

directory.json

Should be compliant, correct me if I'm wrong.
Have a nice evening, everybody.

added Ippensens api-file

---

directory.json

add Cottbus

---

directory.json

as they have a developed community and a bunch of nodes now

add odenthal and overath

---

directory.json

Initiale Anbindung für den API-File.

Import initial reference to API file for Celle Freifunk setup.

---

directory.json

So, wir konnten den IIS leider nicht so schnell zur UTF-8-Mitarbeit für application/json überreden. Hab nun nen Wrapper drum gebaut. Sollte jetzt korrekt ausliefern.

Freifunk Bestwig / Neuer Versuch

---

directory.json

NEA (Neustadt an der Aisch) has been added.

added Neustadt a. d. Aisch

---

directory.json

API file for the new community "Freifunk Herzogtum Lauenburg"

Add API-File "lauenburg" - Herzogtum Lauenburg

---

directory.json

update URLs of Altdorf & Landshut API files

---

directory.json

inkteraktive API-File für Heford eingefuegt: http://map.herford.freifunk.net/freifunk-api/herford.json

api: herford

---

directory.json

same as arnsberg. Just a Layer 2 split and some other contacts / IP ranges

added sundern

---

directory.json

API File im github eingestellt und ein paar Änderungen in der Datei.

Neuer Platz für die API file

---

directory.json

add Neustadt Weinstrasse, Update Weyher

add Neustadt Weinstrasse, Update Weyher

---

directory.json

rename api entry from westpfalz to kaiserslautern and change http to https

rename api entry from westpfalz to kaiserslautern

---

directory.json

remove ostholstein

---

directory.json

add freifunk frankenberg

---

directory.json

Add Freifunk Offenburg/Ortenau to directory.json

Add Freifunk Offenburg/Ortenau to directory.json

---

directory.json

Wir hatten bis jetzt Münchner FW im Einsatz und werden dann jetzt versuchen, auf eigenen Beinen zu stehen.

Kitzingen added

---

directory.json

Added Monheim am Rhein

---

directory.json

Neues API file für Freifunk Kiel

---

directory.json

deliver kiel ffapi.json via https://hopglass.freifunk.in-kiel.de/ffapi.json

move kiel to livedata

---

directory.json

Freifunk in der Stadt Haan hinzugefügt

added new community haan

---

directory.json

WTF
Someone deleted "barntrup".
So I copied it back in the list

Someone deleted Barntrup

---

directory.json

change url of Freifunk Lüneburg .json

update Freifunk Lüneburg

---

directory.json

Tettnang will now provide his API File in the public github too.

Update Freifunk Community Tettnang

---

directory.json

API file für FF Suhl neu erstellt und veröffentlicht.
Bitte einpflegen.

Update directory.json (Freifunk Suhl)

---

directory.json

Hello,
please add our community to the ffapi.
Thanks

Add Timmendorfer Strand to ffapi

---

directory.json

Update ingolstadt URL

---

directory.json

currently we have no active freifunk community anymore (afaik)

removed jena

---

directory.json

Mail from 23.09.2020
https://www.meiksbar.de/technik/freifunk/barnstorf.json
Gruß von
Meik Schmidt

Update barnstorf url

---

directory.json

Fixes issue #638 and prepares dropping this file from Freifunk Hamm github repo (https://github.com/Freifunk-Hamm/ffapi/blob/master/schwerte.json).

#638 Freifunk Schwerte removed

---

README.md

link to license file,
sign-off instructions

#675 link to license file, sign-off instructions

---

directory.json

We've got a new website, new firmware and some new people :)

update url for Freifunk Leipzig

---

directory.json

update porz - Hood of Rhein-Sieg

Update directory.json with porz

---

directory.json

Update location radevormwald-jsonfile](https://github.com/freifunk/directory.api.freifunk.net/pull/717/commits/3bb022cbf60d1c2281276f6a37cd4435e6361618)

Update directory.json Update location radevormwald-jsonfile
