directory.json

API-Eintrag für Freifunk Saar Community hinzugefügt.

add community Saar

---

directory.json

Ich habe die Ausgabe unseres Generators unter http://freifunk.net/api-generator/ getestet. Es sollte jetzt alles stimmen. Auf das erste Request habe ich keine Reaktion mehr erhalten, daher reiche ich es nochmal ein.

Update Wermelskirchen (Versuch 2)

---

directory.json

Hallo,
ich habe im Wiki die Community Düren angelegt und möchte erstmal die Basiseintrag in die Map bekommen. Beim nächsten Treffen ergänzen wir dann weitere Meta Infos.
Beste Grüße
Markus

Community Düren hinzufügen

---

directory.json

URL with Umlauts does not seem to work.
Created new API file at location without umlauts.
See https://github.com/freifunk/directory.api.freifunk.net/pull/139#issuecomment-86127799

Update Location of Dueren API-File

---

directory.json

Freifunk Ibbenbüren ohne Umlaute

Freifunk Ibbenbueren

---

directory.json

ACHTUNG nicht einfach mergen!
Das Thema muss erst gellärt werden. Diskussion siehe #137

changed bamberg to bamberg (Freifunk Franken)

---

directory.json

Neue Metacommunity Stormarn Freifunk, dies ist die API für die Stadt Bad Oldesloe und dessen Umgebung

add Bad Oldesloe

---

directory.json

Hockenheim has been completely merged to Rhein-Neckar, so it can be removed

Remove Hockenheim

---

directory.json

Hallo liebe Directory-Maintainer,
wir haben uns entschlossen, unser API file nun auf Github zu verwalten ([Link][1]). Hier ist die dazu nötige Änderung für das Directory.
Gruß
David
[1]: https://github.com/ffac/api-file

Freifunk Aachen API file now hosted on Github

---

directory.json

Bitte aktualisieren. Ein Domain-Split steht demnächst an und dann kommen die automatisch gesammelten Meta-Daten (Anzahl Nodes und ähnliches) wieder dazu.

Updated URL for Düsseldorf

---

directory.json

http gets a redirect to https. api.json is currently a exception

[TASK] Use https for Freifunk Regensburg api.json

---

directory.json

Die API-File mit den korrigierten Daten wurde nun auf unserem Community Server abgelegt. Ich bitte um Eintragung. Danke!

Update neuer Ablageort neukirchen-vluyn.json

---

directory.json

Freifunk Haßloch als Unter-Community von Freifunk Südpfalz eingetragen

Freifunk Haßloch hinzugefügt

---

directory.json

Neusser API von github auf eigenen Space verschoben

Location Neusser API-File

---

directory.json

Auf Anfrage von Andreas Bräu die Community Freifunk Saar nach Saarbrücken verlegt. Im API-File selber wird in den nächsten Tagen noch Lat und Lon geupdatet.

Freifunk Saar nach Saarbrücken verlegt

---

directory.json

Unsere Freifunk-Community in Ilmenau befindet sich noch in der Entstehung. Im Moment verwenden wir die Firmware von Freifunk Erfurt, damit sind momentan 5-10 Knoten online (z.B. http://map.erfurt.freifunk.net/meshviewer/#!v:m;n:f4f26df2a80a ).

Freifunk Ilmenau hinzugefügt

---

directory.json

We moved our api file from a server of a member to our own community subdomain

Change link for Freifunk Erfurt to new destination

---

directory.json

Pull Request zum hinzufügen der Freifunk Community Freifunk Friedrichshafen, die ein Teil der Metacommunity Freifunk Bodensee ist!

Freifunk Friedrichshafen (Metacommunity Freifunk Bodensee)

---

directory.json

Wir würden gerne die neue Freifunk Community Freifunk Kressbronn, die eine Metacommunity von Freifunk Bodensee ist, in die Freifunk API eintragen. Vielen Dank.

Update directory.json für Metacommunity Freifunk Bodensee

---

directory.json

The Schoeneck API file wasn't update since more than a year. So it should be removed from the directory and replaced by the automatically generated API file.
There were also some activities by Freifunk Vogtland in regions which weren't yet listed in the directory.
* Ellefeld
* Heinsdorfergrund
* Mühlental
* Neuensalz
* Neumark
* Pöhl
* Steinberg

Update Freifunk Vogtland

---

directory.json

Warendorf ist eine Subcommunity des Münsterlandes und nutzt die Infrastruktur des Münsterlandes wie viele andere Subcommunites auch. Da die anderen Subcommunities auch nicht eigenständig hier hinterlegt sind, ergibt es aus unserer Sicht keinen Sinn, Warendorf separat aufzuführen.

Warendorf entfernt

---

directory.json

API-Entry for FF Esslingen a. N.
(Nicht zu verwechseln mit Essingen)

Add Esslingen

---

directory.json

freifunk-hagen.de wird nur nach freifunk-hagen.net weitergeleitet.
Sie korrekte Adresse lautet https://freifunk-hagen.net

Hagen https://freifunk-hagen.net

---

directory.json

unsere ffapi url hat sich geändert, bitte aktualisieren.

darmstadt: update url

---

directory.json

New aktive subcommunity "bodman-ludwigshafen" from Meta-Community [Freifunk Bodensee](https://ffbsee.net)

add community bodman-ludwigshafen

---

directory.json

Hello,
I have updated the API file for rheinbach and moved the file to our web-servers root directory.
[freifunk-rheinbach.de](https://freifunk-rheinbach.de/freifunk-rheinbach-api.json
Best regards
Thomas

API file for rheinbach updated and moved to web-server

---

directory.json

Community Gronau existiert nicht mehr. Homepage schon länger offline. Facebook Gruppe verweist und reagieren nicht auf anfragen. 
Siehe auch: https://forum.freifunk.net/t/kontaktgesuch-freifunk-gronau-vfn-nrw/20151

Gronau entfernt.

---

directory.json

Neue json-File mit richtigem Link: https://www.meiksbar.de/technik/freifunk/barnstorf.json

Neue Freifunk Community aus Barnstorf

---

directory.json

Hi,
wir machen jetzt auch etwas Freifunk in Wolfen.
Ich folge der Anleitung:
- https://freifunk.net/wie-mache-ich-mit/lokale-gruppe-gruenden/ ->
- https://blog.freifunk.net/2014/03/25/6-schritten-zum-apifile/

Freifunk Wolfen

---

directory.json

Since the Domain has a valid cert, we could just start using it.

mannheim: change http to https

---

directory.json

Eingang per Mail:
Hi,
ich habe meine Website in in ein CMS migriert. Da hat sich dann die Dateistruktur geändert:
https://www.meiksbar.de/files/freifunk/barnstorf.json
Gruß Meik Schmidt

Update Url barnstorf

---

directory.json

Ortenau got it's own website again this year, so it only makes sense to move the directory API file there. The API file has also changed (new meetup location).

update location of offenburg/ortenau

---

directory.json

Fixes issue #636 and prepares dropping this file from Freifunk Hamm github repo (https://github.com/Freifunk-Hamm/ffapi/blob/master/luenen.json).

#636 Freifunk Lünen removed

---

directory.json

API file for willich is outdated.
There is no active Freifunk Community in Willich anymore.
All its routers had been moved to Freifunk Niersufer, as Fabian Törper confirmed this week.
Sad to say, but it is time to delete Freifunk Willich from API directory.
I will delete the old API file of Freifunk Willich from github repo, when is has been deleted from API directory.
https://github.com/Freifunk-Hamm/ffapi/blob/master/willich.json

#640 API file of Freifunk Willich deleted

---

directory.json

This community is gone.
Website http://freifunk-meschede.net is gone.
Domain is no longer registered.
Its facebook pages is gone.
Its meta community (Freifunk Möhne) has gone, too.
See: https://www.freifunk-moehne.net/ for details.
Entry of Freifunk Meschede in API directory brings CI to fail: https://travis-ci.org/github/freifunk/directory.api.freifunk.net/builds/772697472

#644 Freifunk Meschede deleted

---

directory.json

API file for viersen is outdated.
There is no active Freifunk Community in Viersen anymore.
All its routers had been moved to Freifunk Niersufer, as Fabian Törper confirmed this week.
Sad to say, but it is time to delete Freifunk Viersen from API directory.
I will delete the old API file of Freifunk Viersen from github repo, when is has been deleted from API directory.
https://github.com/Freifunk-Hamm/ffapi/blob/master/viersen.json

#641 API file of Freifunk Viersen deleted

---

directory.json

Facebook Page of Freifunk Krefeld was not updated since 2017:
https://www.facebook.com/Freifunk.Krefeld/
Website has gone.
End-of-life notice was published at: https://wiki.freifunk.net/Freifunk_Krefeld
API file for krefeld is outdated.
There is no active Freifunk Community in Krefeld anymore.
All its routers had been moved to Freifunk Niersufer, as Fabian Törper confirmed last week.
Sad to say, but it is time to delete Freifunk Krefeld from API directory.
Fabian Törper (Freifunk Niersufer) will delete the old API file of Freifunk Krefeld from github repo:
https://raw.githubusercontent.com/ffniers/ffapi/master/krefeld.json
when is has been deleted from API directory.

#648 Freifunk Krefeld deleted

---

directory.json

API file for nettetal is outdated.
There is no active Freifunk Community in Nettetal anymore.
All its routers had been moved to Freifunk Niersufer, as Fabian Törper confirmed this week.
Sad to say, but it is time to delete Freifunk Nettetal from API directory.
I will delete the old API file of Freifunk Nettetal from github repo, when is has been deleted from API directory.
https://github.com/Freifunk-Hamm/ffapi/blob/master/nettetal.json

#651 Freifunk Nettetal is incoporated into Freifunk Niersufer

---

directory.json

API file for kleve is outdated.
There is no active Freifunk Community in Kleve anymore.
All its routers had been moved to Freifunk Niersufer, as Fabian Törper confirmed last week.
Sad to say, but it is time to delete Freifunk Kleve from API directory.
I will delete the old API file of Freifunk Kleve from github repo, when is has been deleted from API directory.
https://github.com/Freifunk-Hamm/ffapi/blob/master/kleve.json

#652 Freifunk Kleve is incoporated into Freifunk Niersufer

---

directory.json

API file for moers is outdated.
There is no active Freifunk Community in Moers anymore.
All its routers had been moved to Freifunk Niersufer, as Fabian Törper confirmed last week.
Sad to say, but it is time to delete Freifunk Moers from API directory.
I will delete the old API file of Freifunk Moers from github repo, when is has been deleted from API directory.
https://github.com/Freifunk-Hamm/ffapi/blob/master/moers.json

#656 Freifunk Moers is incoporated into Freifunk Niersufer

---

directory.json

Clean & fresh PR:
API file for moenchengladbach is outdated.
There is no active Freifunk Community in Mönchengladbach anymore.
All its routers had been moved to Freifunk Niersufer, as Fabian Törper confirmed last week.
Sad to say, but it is time to delete Freifunk Mönchengladbach from API directory.
I will delete the old API file of Freifunk Mönchengladbach from github repo, when is has been deleted from API directory.
https://github.com/Freifunk-Hamm/ffapi/blob/master/moenchengladbach.json

#655 Freifunk Mönchengladbach is incoporated into Freifunk Niersufer 

---

directory.json

Freifunk Niersufer API file is now hosting all cities nearby (single v0.4.16 instead of a collection of per-city API files).
File was created together with Fabian Törper (Freifunk Niersufer).

#667 add niersufer

---

directory.json

API is offline.
I got response from Freifunk Langweid, that community is "dead" and that we are allowed to delete their API file from Freifunk API directory.

#662 langweid deleted

---

directory.json

Über 9 Monate
25.08.2021 19:01
hassloch, https://www.freifunk-hassloch.de/freifunk-hassloch.json
Freifunk Haßloch, Haßloch
<class 'urllib.error.URLError'> <urlopen error [Errno 113] No route to host>
SocketException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 176.9.132.123:443
github@ib-leier.net

delete hassloch (25.08.2021)

---

directory.json

Über 9 Monate
28.08.2021 00:01
enkreis, https://karte.ff-en.de/ffapi/en.json
Freifunk im Ennepe-Ruhr-Kreis, Ennepe-Ruhr-Kreis
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
@Kilobyte22 
Auf meine Mails gibt die ganze Zeit die automatosche Antwort: "In Kürze erhalten Sie eine individuelle Antwort.".
Matthias und Lars hatte ich extra angeschrieben.
Leider gibt es keine weiteren Antworten.
Signed-off-by: O.Leier <github@ib-leier.net>

delete enkreis (28.08.2021)

---

directory.json

has always been only a placeholder and never was a distinct community, therefore we removed the API file.

directory.json: remove landshut.freifunk.net

---

directory.json

add Petershagen/Eggersdorf to community list

---

directory.json

as Freifunk Ulm stops operations, ffmuc tries to take over the nodes 
to update the node count arrocding to the new gluon firmware the api is now in our FFMUC Repo

Update Ulm Api to FFMUC Repo

---

directory.json

Added Hildesheim

---

directory.json

The FFMD (Freifunk Magdeburg) project has been closed.

Remove entry for magdeburg (FFMD)

---

directory.json

FreifunkUE moved a year ago to 4830.org's servers and shut down their own firmware and map servers. Hence we should move the API file accordingly.

Freifunk Uelzen moved in July, 2024, onto the 4830.org e. V. platform
